// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/audit" | "/admin/catalogs" | "/admin/classes" | "/admin/classes/[id]" | "/admin/communications" | "/admin/notifications" | "/admin/payments" | "/admin/professors" | "/admin/professors/[id]" | "/admin/profile" | "/admin/reports" | "/admin/sessions/[id]" | "/admin/settings" | "/admin/students" | "/admin/students/[id]" | "/admin/users" | "/clases" | "/clases/[slug]" | "/contacto" | "/forgot-password" | "/horarios" | "/login" | "/profesores" | "/profesores/[slug]" | "/professor" | "/professor/calendar" | "/professor/classes" | "/professor/classes/[id]" | "/professor/profile" | "/professor/sessions/[id]" | "/professor/students" | "/professor/students/[id]" | "/reset-password"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/professor"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/audit": {}
  "/admin/catalogs": {}
  "/admin/classes": {}
  "/admin/classes/[id]": { "id": string; }
  "/admin/communications": {}
  "/admin/notifications": {}
  "/admin/payments": {}
  "/admin/professors": {}
  "/admin/professors/[id]": { "id": string; }
  "/admin/profile": {}
  "/admin/reports": {}
  "/admin/sessions/[id]": { "id": string; }
  "/admin/settings": {}
  "/admin/students": {}
  "/admin/students/[id]": { "id": string; }
  "/admin/users": {}
  "/clases": {}
  "/clases/[slug]": { "slug": string; }
  "/contacto": {}
  "/forgot-password": {}
  "/horarios": {}
  "/login": {}
  "/profesores": {}
  "/profesores/[slug]": { "slug": string; }
  "/professor": {}
  "/professor/calendar": {}
  "/professor/classes": {}
  "/professor/classes/[id]": { "id": string; }
  "/professor/profile": {}
  "/professor/sessions/[id]": { "id": string; }
  "/professor/students": {}
  "/professor/students/[id]": { "id": string; }
  "/reset-password": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/professor": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
