// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(public)/clases/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clases/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/clases/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/clases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clases">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/clases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/horarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/horarios">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/horarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/profesores/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profesores/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/profesores/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/profesores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profesores">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/profesores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/catalogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalogs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/catalogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/classes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/classes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/classes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/classes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/communications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communications">> = Specific
  const handler = {} as typeof import("../../src/app/admin/communications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/admin/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/professors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/professors/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/professors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/professors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/professors">> = Specific
  const handler = {} as typeof import("../../src/app/admin/professors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/sessions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/sessions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/students/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/students/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/students/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/students">> = Specific
  const handler = {} as typeof import("../../src/app/admin/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/professor/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/classes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/classes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/professor/classes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/classes">> = Specific
  const handler = {} as typeof import("../../src/app/professor/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor">> = Specific
  const handler = {} as typeof import("../../src/app/professor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/profile">> = Specific
  const handler = {} as typeof import("../../src/app/professor/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/sessions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/professor/sessions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/students/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/students/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/professor/students/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/students">> = Specific
  const handler = {} as typeof import("../../src/app/professor/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/professor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/professor">> = Specific
  const handler = {} as typeof import("../../src/app/professor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
